extraction:
  cpp:
    configure:
      command:
      - "./bootstrap --no-git --skip-po --no-bootstrap-sync --gnulib-srcdir=gnulib"
      - "./configure --disable-tests --disable-doc --disable-gtk-doc"
    index:
      build_command: "make"
